OPENAI_API_KEY = "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"

OPENWEATHER_API_KEY = "1d9053d3bfb37fd39be6ba28f8df776f"
GOOGLE_MAPS_API_KEY = "AIzaSyD1jPnPwE5-0gkyCeNzPkK14-TIwiQS8FY"
EVENTBRITE_API_KEY = "DVN3NGWDCAIND2S5CSUC"