OPENAI_API_KEY = "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"

OPEN_API_KEY = ''